//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polizas.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoberturaPoliza
    {
        public int Id { get; set; }
        public Nullable<int> id_poliza { get; set; }
        public string cobertura { get; set; }
    
        public virtual Poliza Poliza { get; set; }
    }
}
